---
- name: Allow SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp
  notify: reload ufw

- name: Allow DERP TCP ports 80 and 443
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
  notify: reload ufw

- name: Allow STUN UDP 3478
  ufw:
    rule: allow
    port: 3478
    proto: udp
  notify: reload ufw

- name: Enable UFW
  command: ufw --force enable
  notify: reload ufw

- name: Add IP Blacklisting
  template:
    src: ip-blacklisting.sh.j2
    dest: /usr/local/bin/ip-blacklister.sh
    mode: 0744

- name: Block IPs
  cron:
    name: "Daily IP Blacklist"
    user: root
    minute: "0"
    hour: "5"
    job: "/usr/local/bin/ip-blacklister.sh"

- name: Add config for fail2ban
  template:
    src: defaults-debian.conf.j2
    dest: /etc/fail2ban/jail.d/defaults-debian.conf
    mode: 0644
  notify: reload fail2ban

- name: Add API Key to Report to AbuseIPDB
  lineinfile:
    path: /etc/fail2ban/action.d/abuseipdb.conf
    regexp: '^abuseipdb_apikey'
    line: "abuseipdb_apikey = {{ abuseipdb_apikey }}"
  when:
    - report_to_abuseipdb | default(false)
    - abuseipdb_apikey is defined
    - abuseipdb_apikey | trim | length > 0
  notify: reload fail2ban
